# -*- coding: utf-8 -*-
"""Fake_news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_CpF9u6ogAN6Svt6qM4bn28uiOXCEd4
"""

import pandas as pd
import numpy as np

true = pd.read_csv('True.csv')
fake = pd.read_csv('Fake.csv')
true['label'] = 1
fake['label'] = 0

news = pd.concat([true, fake] , axis = 0)
news.head()

news = news.drop(['title','subject','date'] , axis = 1)

news.head()

news = news.sample(frac =1)

news.head()

news.reset_index(inplace =True)

news = news.drop(['index'] , axis =1)

news.head()

import re

def wordopt(text) :
  text = text.lower()
  text = re.sub(r'https?://\S+|www\.\S' ,'',text)
  text = re.sub(r'<.*?>' ,'',text)
  text = re.sub(r'[^\w\s]','',text)
  text = re.sub(r'\d' ,'',text)
  text = re.sub(r'\n' ,' ',text)
  return text

news['text'] = news['text'].apply(wordopt)

news['text']

x = news['text']
y = news['label']

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report

from numpy.random.mtrand import random
x_train , x_test ,y_train , y_test = train_test_split(x,y,test_size= 0.3,random_state=42)

vectorizer = TfidfVectorizer()
xv_train = vectorizer.fit_transform(x_train)
xv_test = vectorizer.transform(x_test)

from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train,y_train)

pred_lr = LR.predict(xv_test)

LR.score(xv_test,y_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,pred_lr))

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(xv_train,y_train)

dtc.score(xv_test,y_test)

pred_dtc = dtc.predict(xv_test)
print(classification_report(y_test , pred_dtc))

from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(random_state=0)
gbc.fit(xv_train,y_train)

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
rfc.fit(xv_train,y_train)
predict_rfc = rfc.predict(xv_test)

rfc.score(xv_test,y_test)

print(classification_report(y_test,predict_rfc))